# server port
server:
    port: 8093

    error:
      include-stacktrace: always

spring:
  # console ansi setting
  output:
    ansi:
      enable: always

  # datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharesiteDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  # JPA setting
  jpa:
    database: mysql
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Email 인증 관련
  mail:
    host: smtp.gmail.com
    port: 587
    username: ljs528022@gmail.com
    password: jooc bfom xkwl uehn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Multipary 관련
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 30MB

  web:
    resources:
      static-locations: file:///C:/MyDev/uploads/


  # Security setting
  security:
    user:
      name: user
      password: 0000

logging:
    level:
      org:
        springframework:
          security: DEBUG

#Mybatis config
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  # upload setting
  upload:
    path: upload

jwt:
  secret-key: kPn0cEAt8+QSRynzRhWQw6uFpp9KzC37yQsZzD6MxK4=

file:
  upload-dir: C:\MyDev\uploads