# server port
server:
    port: 8093

    error:
      include-stacktrace: always

spring:
  output:
    ansi:
      enable: always

  redis:
    host: localhost
    port: 6379

  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:templates/ss/

  #datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharesiteDB?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  security:
    user:
      name: user
      password: 1234

#Mybatis config
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:

  # paging setting
  pagination:
    write_pages: 10
    page_rows: 10

  # upload setting
  upload:
    path: upload