# server port
server:
    port: 8093

    error:
      include-stacktrace: always

spring:
  # console ansi setting
  output:
    ansi:
      enable: always

  # thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:templates/ss/

  # datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharesiteDB?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  # JPA setting
  jpa:
    database: mysql
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Security setting
  security:
    user:
      name: user
      password: 0000

#Mybatis config
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:

  # paging setting
  pagination:
    write_pages: 10
    page_rows: 10

  # upload setting
  upload:
    path: upload